"""Add kis_tokens table

Revision ID: 151b5be6bb4c
Revises: 313693c7097d
Create Date: 2025-08-27 13:25:45.586654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '151b5be6bb4c'
down_revision: Union[str, None] = '313693c7097d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kis_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False, comment='KIS 접근 토큰'),
    sa.Column('expires_at', sa.DateTime(), nullable=False, comment='토큰 만료 시간'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kis_tokens_id'), 'kis_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_kis_tokens_user_id'), 'kis_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kis_tokens_user_id'), table_name='kis_tokens')
    op.drop_index(op.f('ix_kis_tokens_id'), table_name='kis_tokens')
    op.drop_table('kis_tokens')
    # ### end Alembic commands ###
