"""add realized profit columns to transactions

Revision ID: 8ab48f210080
Revises: 3b63496be4c2
Create Date: 2025-08-31 17:00:08.622009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ab48f210080'
down_revision: Union[str, None] = '3b63496be4c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('idx_holdings_broker', table_name='holdings')
    op.create_index(op.f('ix_holdings_broker_id'), 'holdings', ['broker_id'], unique=False)
    op.add_column('transactions', sa.Column('avg_cost_at_transaction', sa.DECIMAL(precision=15, scale=6), nullable=True, comment='매도 시점의 평균단가 (해당 통화)'))
    op.add_column('transactions', sa.Column('realized_profit_per_share', sa.DECIMAL(precision=15, scale=6), nullable=True, comment='주당 실현손익 (해당 통화)'))
    op.add_column('transactions', sa.Column('total_realized_profit', sa.DECIMAL(precision=15, scale=2), nullable=True, comment='총 실현손익 (해당 통화)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'total_realized_profit')
    op.drop_column('transactions', 'realized_profit_per_share')
    op.drop_column('transactions', 'avg_cost_at_transaction')
    op.drop_index(op.f('ix_holdings_broker_id'), table_name='holdings')
    # op.create_index('idx_holdings_broker', 'holdings', ['broker_id'], unique=False)
    # ### end Alembic commands ###
