# 한국어 번역 매핑(주요 항목)
INCOME_KR = {
  'Tax Effect Of Unusual Items': '특이항목의 세금 효과',
  'Tax Rate For Calcs': '계산에 사용된 세율',
  'Normalized EBITDA': '정상화된 EBITDA',
  'Net Income From Continuing Operation Net Minority Interest': '계속영업 순이익(비지배지분 차감)',
  'Reconciled Depreciation': '감가상각비',
  'Reconciled Cost Of Revenue': '조정된 매출원가',
  'EBITDA': 'EBITDA',
  'EBIT': 'EBIT',
  'Net Interest Income': '순이자수익',
  'Interest Expense': '이자비용',
  'Interest Income': '이자수익',
  'Normalized Income': '정상화 순이익',
  'Net Income From Continuing And Discontinued Operations': '계속/중단영업 순이익',
  'Total Expenses': '총비용',
  'Total Operating Income As Reported': '보고된 영업이익',
  'Diluted Average Shares': '희석주식수 평균',
  'Basic Average Shares': '기본주식수 평균',
  'Diluted EPS': '희석주당순이익(EPS)',
  'Basic EPS': '기본주당순이익(EPS)',
  'Diluted NI Availto Com Stockholders': '희석기준 보통주주 귀속순이익',
  'Net Income Common Stockholders': '보통주주 순이익',
  'Net Income': '순이익',
  'Net Income Including Noncontrolling Interests': '비지배지분 포함 순이익',
  'Net Income Continuous Operations': '계속영업 순이익',
  'Tax Provision': '법인세비용',
  'Pretax Income': '법인세차감전 순이익',
  'Other Income Expense': '기타수익/비용',
  'Other Non Operating Income Expenses': '기타영업외수익/비용',
  'Net Non Operating Interest Income Expense': '영업외 순이자수익/비용',
  'Interest Expense Non Operating': '영업외 이자비용',
  'Interest Income Non Operating': '영업외 이자수익',
  'Operating Income': '영업이익',
  'Operating Expense': '영업비용',
  'Research And Development': '연구개발비',
  'Selling General And Administration': '판매비와관리비',
  'Gross Profit': '매출총이익',
  'Cost Of Revenue': '매출원가',
  'Total Revenue': '총수익',
  'Operating Revenue': '영업수익',
}

BALANCE_KR = {
  'Treasury Shares Number': '자기주식 수',
  'Ordinary Shares Number': '보통주식 수',
  'Share Issued': '발행주식 수',
  'Net Debt': '순부채',
  'Total Debt': '총부채',
  'Cash Cash Equivalents And Short Term Investments': '현금및단기금융상품',
  'Other Short Term Investments': '기타단기금융상품',
  'Cash And Cash Equivalents': '현금및현금성자산',
  'Cash Equivalents': '현금성자산',
  'Cash Financial': '금융성현금',
}

CASHFLOW_KR = {
  'Free Cash Flow': '잉여현금흐름',
  'Repurchase Of Capital Stock': '자기주식 매입',
  'Repayment Of Debt': '부채 상환',
  'Issuance Of Debt': '부채 발행',
  'Issuance Of Capital Stock': '자본 발행',
  'Capital Expenditure': '설비투자(자본적지출)',
  'Interest Paid Supplemental Data': '이자지급(보조자료)',
  'Income Tax Paid Supplemental Data': '법인세지급(보조자료)',
  'End Cash Position': '기말현금잔고',
  'Beginning Cash Position': '기초현금잔고',
  'Changes In Cash': '현금변동',
  'Financing Cash Flow': '재무활동현금흐름',
  'Cash Flow From Continuing Financing Activities': '계속영업 재무활동현금흐름',
  'Net Other Financing Charges': '기타 재무비용 순액',
  'Cash Dividends Paid': '현금배당금 지급',
  'Common Stock Dividend Paid': '보통주 배당금 지급',
  'Net Common Stock Issuance': '보통주 순발행',
  'Common Stock Payments': '보통주 지급',
  'Common Stock Issuance': '보통주 발행',
  'Net Issuance Payments Of Debt': '부채 순발행/지급',
  'Net Short Term Debt Issuance': '단기부채 순발행',
  'Net Long Term Debt Issuance': '장기부채 순발행',
  'Long Term Debt Payments': '장기부채 상환',
  'Long Term Debt Issuance': '장기부채 발행',
  'Investing Cash Flow': '투자활동현금흐름',
  'Cash Flow From Continuing Investing Activities': '계속영업 투자활동현금흐름',
  'Net Other Investing Changes': '기타 투자변동 순액',
  'Net Investment Purchase And Sale': '투자매입 및 매각 순액',
  'Sale Of Investment': '투자자산 매각',
  'Purchase Of Investment': '투자자산 매입',
  'Net Business Purchase And Sale': '사업인수/매각 순액',
  'Purchase Of Business': '사업인수',
  'Net PPE Purchase And Sale': '유형자산(PPE) 순매입/매각',
  'Purchase Of PPE': '유형자산(PPE) 매입',
  'Operating Cash Flow': '영업활동현금흐름',
  'Cash Flow From Continuing Operating Activities': '계속영업 영업활동현금흐름',
  'Change In Working Capital': '운전자본 변동',
  'Change In Other Working Capital': '기타 운전자본 변동',
  'Change In Other Current Liabilities': '기타 유동부채 변동',
  'Change In Other Current Assets': '기타 유동자산 변동',
  'Change In Payables And Accrued Expense': '미지급금 및 발생비용 변동',
  'Change In Payable': '미지급금 변동',
  'Change In Account Payable': '매입채무 변동',
  'Change In Inventory': '재고자산 변동',
  'Change In Receivables': '매출채권 변동',
  'Changes In Account Receivables': '매출채권 변동(세부)',
  'Other Non Cash Items': '기타 비현금성 항목',
  'Stock Based Compensation': '주식보상비용',
  'Deferred Tax': '이연법인세',
  'Deferred Income Tax': '이연법인세(소득세)',
  'Depreciation Amortization Depletion': '감가상각비/무형자산상각/고갈비',
  'Depreciation And Amortization': '감가상각비 및 무형자산상각',
  'Net Income From Continuing Operations': '계속영업 순이익',
}